### ISSUE TITLE
traceback on invalid option

### ISSUE THREAD

**Issue by keszybz** [rpm-software-management/dnf-plugin-system-upgrade#19]
Not a big issue, but it would be nice to suppress the traceback, and only print the error message:

```
[test@fedora22 ~]$ sudo dnf system-upgrade --releasever 23 download --distrosync
Traceback (most recent call last):
  File "/bin/dnf", line 36, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
  File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 198, in user_main
    errcode = main(args)
  File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 84, in main
    return _main(base, args)
  File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 117, in _main
    cli.configure(map(ucd, args))
  File "/usr/lib/python2.7/site-packages/dnf/cli/cli.py", line 1029, in configure
    self.command.configure(self.base.extcmds)
  File "/usr/lib/python2.7/site-packages/dnf-plugins/system_upgrade.py", line 263, in configure
    self.opts = self.parse_args(args)
  File "/usr/lib/python2.7/site-packages/dnf-plugins/system_upgrade.py", line 254, in parse_args
    opts = p.parse_args(extargs)
  File "/usr/lib64/python2.7/argparse.py", line 1704, in parse_args
    self.error(msg % ' '.join(argv))
  File "/usr/lib/python2.7/site-packages/dnf-plugins/system_upgrade.py", line 206, in error
    raise AttributeError(message)
AttributeError: unrecognized arguments: --distrosync
```

dnf-1.1.1-2.fc22.noarch
dnf-plugin-system-upgrade-0.4.1-1.fc22.noarch

**Comment by wgwoods** [comment]
Should be fixed by 509ce20539117f18584c39bf8e4facb8ff5e12e9.
