### ISSUE TITLE
dnf system-upgrade reboot fails: unable to upgrade from f26 to f27

### ISSUE THREAD

**Issue by aanno** [rpm-software-management/dnf-plugin-system-upgrade#58]
This is what I find in `/var/log/dnf.log`:

```
2017-11-14T17:56:17Z DEBUG Kann nicht herunterladen 'https://mirrors.fedoraproject.org/metalink?repo=updates-released-f27
&arch=x86_64': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedorap
roject.org/metalink?repo=updates-released-f27&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org].
2017-11-14T17:56:17Z DDEBUG Cleaning up.
2017-11-14T17:56:17Z SUBDEBUG
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf/repo.py", line 229, in _perform
    return super(_Handle, self).perform(result)
  File "/usr/lib64/python3.6/site-packages/librepo/__init__.py", line 1522, in perform
    _librepo.Handle.perform(self, result)
librepo.LibrepoException: (8, "Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https:/
/mirrors.fedoraproject.org/metalink?repo=updates-released-f27&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.
org]", 'An Curl handle error')
```

However, on my command line, curl works:
```
$ curl https://mirrors.fedoraproject.org/metalink?repo=updates-released-f27&arch=x86_6
<?xml version="1.0" encoding="utf-8"?>
<metalink version="3.0" xmlns="http://www.metalinker.org/" type="dynamic" pubdate="Tue, 14 Nov 2017 18:51:33 GMT" generator="mirrormanager" xmlns:mm0="http://fedorahosted.org/mirrormanager">
<!--
# either path=, or repo= and arch= must be specified
-->
</metalink>
```
I tried if this a IPv6 problem in the line of https://ask.fedoraproject.org/en/question/32319/could-not-resolve-host-mirrorsfedoraprojectorg/ but:

```
$ curl -6 https://mirrors.fedoraproject.org/metalink?repo=updates-released-f27&arch=x86_6
<?xml version="1.0" encoding="utf-8"?>
<metalink version="3.0" xmlns="http://www.metalinker.org/" type="dynamic" pubdate="Tue, 14 Nov 2017 18:53:36 GMT" generator="mirrormanager" xmlns:mm0="http://fedorahosted.org/mirrormanager">
<!--
# either path=, or repo= and arch= must be specified
-->
</metalink>
```

**Comment by aanno** [comment]
I also opened a ticket on the redhat tracking system for this: https://bugzilla.redhat.com/show_bug.cgi?id=1513111

**Comment by aanno** [comment]
Using the alternative upgrade procedure with `fedora-upgrade` (https://fedoraproject.org/wiki/Upgrading_Fedora_using_package_manager) has worked for me.

I also updated another fedora host with dnf-plugin-system-upgrade without any problems, i.e. I was not able to reproduce the problem on another machine.

**Comment by gordonmessmer** [comment]
The bug appears to be that dnf processes the last metadata update time while in the offline system-upgrade mode.  I was able to work around the problem by re-running "dnf system-upgrade download --releasever 27" immediately before "dnf system-upgrade reboot"

**Comment by MightyCreak** [comment]
I have tried to upgrade two of my machines to 27 and I've had the same symptoms twice: I run `sudo dnf system-upgrade reboot`, it reboots, fails to upgrade, reboots again, and comes back to Fedora 26.

I've also tried to disable all my extra repos (just in case, since I didn't have to do that when going from 25 to 26), but same result.

I've tried @gordonmessmer's workaround, but it doesn't work either.

**Comment by gordonmessmer** [comment]
@MightyCreak Check /var/log/dnf.log and verify that it records a line near the end similar to:

2017-11-16T23:32:49Z DEBUG Cannot download 'https://mirrors.fedoraproject.org/metalink?repo=updates-released-f27&arch=x86_64': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f27&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org].

If you see something else, please open a new bug.  

If you see an entry similar to that one, it should indicate which repository's metadata is expiring, and you'll need to check that one for a short "metadata_expire" setting, or another reason it might try to refresh while offline.

**Comment by MightyCreak** [comment]
I got the same kind of error (but in French):

```
2017-11-20T03:08:52Z DDEBUG Base command: system-upgrade
2017-11-20T03:08:52Z DDEBUG Extra commands: ['--releasever=27', 'system-upgrade', 'upgrade']
2017-11-20T03:09:15Z DEBUG Impossible de télécharger « https://copr-be.cloud.fedoraproject.org/results/taw/Riot/fedora-27-x86_64/ » : Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried.
2017-11-20T03:09:15Z DEBUG dépôt : utilisation du cache pour : adobe-linux-x86_64
2017-11-20T03:09:15Z DEBUG not found deltainfo for: Adobe Systems Incorporated
2017-11-20T03:09:15Z DEBUG not found updateinfo for: Adobe Systems Incorporated
2017-11-20T03:09:15Z DEBUG adobe-linux-x86_64 : utilisation des métadonnées depuis le jeu 26 oct 2017 00:39:15 EDT.
2017-11-20T03:09:15Z DEBUG dépôt : utilisation du cache pour : fedora-steam
2017-11-20T03:09:15Z DEBUG not found deltainfo for: negativo17 - Steam
2017-11-20T03:09:15Z DEBUG not found updateinfo for: negativo17 - Steam
2017-11-20T03:09:15Z DEBUG fedora-steam : utilisation des métadonnées depuis le jeu 16 nov 2017 10:33:07 EST.
2017-11-20T03:09:15Z DEBUG Impossible de télécharger « https://mirrors.fedoraproject.org/metalink?repo=updates-released-f27&arch=x86_64 » : Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f27&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org].
2017-11-20T03:09:15Z DDEBUG Cleaning up.
2017-11-20T03:09:15Z SUBDEBUG 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf/repo.py", line 229, in _perform
    return super(_Handle, self).perform(result)
  File "/usr/lib64/python3.6/site-packages/librepo/__init__.py", line 1522, in perform
    _librepo.Handle.perform(self, result)
librepo.LibrepoException: (8, "Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f27&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]", 'An Curl handle error')
```

This repo seems to be obsolete, should we report this bug in the given repo?
https://github.com/rpm-software-management/dnf-plugins-extras

**Comment by ozeszty** [comment]
This workaround let me perform an upgrade: https://bugzilla.redhat.com/show_bug.cgi?id=1513111#c9
