### ISSUE TITLE
'systemctl reboot' at end of upgrade returns.. -15?

### ISSUE THREAD

**Issue by wgwoods** [rpm-software-management/dnf-plugin-system-upgrade#6]
After the upgrade completes, we try to run `systemctl reboot`, but for some reason it exits with the mysterious (and suspicious) exit code -15, causing a traceback:

``` python-traceback
Traceback (most recent call last):
File "/usr/bin/dnf", line 36, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 193, in user_main
    errcode = main(args)
File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 84, in main
    return _main(base, args)
File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 150, in _main
    cli.command.run_transaction()
File "/usr/lib/python2.7/site-packages/dnf-plugins/system_upgrade.py", line 257, in run_transaction
    self._call_sub("transaction")
File "/usr/lib/python2.7/site-packages/dnf-plugins/system_upgrade.py", line 262, in _call_sub
    subfunc(*args)
File "/usr/lib/python2.7/site-packages/dnf-plugins/system_upgrade.py", line 410, in transaction_upgrade
    reboot()
File "/usr/lib/python2.7/site-packages/dnf-plugins/system_upgrade.py", line 59, in reboot
    check_call(["systemctl", "reboot"])
File "/usr/lib64/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['systemctl', 'reboot']' returned non-zero exit status -15
```

Luckily, this failure causes the system to reboot anyway, as shown in the logs:

```
dnf[622]: Complete!
dnf[622]: Cleaning up downloaded data...
dnf[622]: Traceback (most recent call last):
          [traceback]
systemd[1]: dnf-system-upgrade.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: Stopped System Upgrade.
systemd[1]: dnf-system-upgrade.service: Unit entered failed state.
systemd[1]: dnf-system-upgrade.service: Failed with result 'exit-code'.
systemd[1]: Rebooting as result of failure.
```

But that's pretty weird. We use the same `reboot()` function in `dnf system-upgrade reboot`, so we know it works _outside_ of the upgrade. So: why would `systemctl reboot` return -15 at the end of the upgrade?

Maybe the upgrade itself is the cause of the problem, since we (might) be mixing a new `systemctl` with an older `systemd`? Maybe re-executing `systemd` before reboot would fix this?

We should investigate and figure this out!

**Comment by wgwoods** [comment]
Well, here's a slightly different error, while trying to go from F21 (dnf 0.6.x, plugin 0.5.x) to F22:

```
dnf[600]: Complete!
dnf[600]: Cleaning up downloaded data...
dnf[600]: Failed to start reboot.target: Access denied
dnf[600]: Traceback (most recent call last):
dnf[600]: File "/usr/bin/dnf", line 36, in <module>
dnf[600]: main.user_main(sys.argv[1:], exit_code=True)
dnf[600]: File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 185, in user_main
dnf[600]: return 0
dnf[600]: File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 84, in main
dnf[600]: return _main(base, args)
dnf[600]: File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 145, in _main
dnf[600]: except dnf.exceptions.DepsolveError as e:
dnf[600]: File "/usr/lib/python2.7/site-packages/dnf-plugins/system_upgrade.py", line 276, in run_transaction
dnf[600]: self._call_sub("transaction")
dnf[600]: File "/usr/lib/python2.7/site-packages/dnf-plugins/system_upgrade.py", line 281, in _call_sub
dnf[600]: subfunc(*args)
dnf[600]: File "/usr/lib/python2.7/site-packages/dnf-plugins/system_upgrade.py", line 436, in transaction_upgrade
dnf[600]: reboot()
dnf[600]: File "/usr/lib/python2.7/site-packages/dnf-plugins/system_upgrade.py", line 59, in reboot
dnf[600]: check_call(["systemctl", "reboot"])
dnf[600]: File "/usr/lib64/python2.7/subprocess.py", line 540, in check_call
dnf[600]: raise CalledProcessError(retcode, cmd)
dnf[600]: subprocess.CalledProcessError: Command '['systemctl', 'reboot']' returned non-zero exit status 4
```

So this time we're exiting with status 4? Weird. Still, here's the key thing:

```
dnf[600]: Failed to start reboot.target: Access denied
```

I've heard rumbling on #fedora-qa that this might be a SELinux thing, so that should get investigated further.

**Comment by keszybz** [comment]
Looks like a systemd problem (the selinux hypothesis looks reasonable). I don't think this plugin is doing anything wrong.

**Comment by hhorak** [comment]
selinux bug https://bugzilla.redhat.com/show_bug.cgi?id=1263570

**Comment by wgwoods** [comment]
well OK then - closing this issue, since the bug is being tracked elsewhere.
